### ISSUE TITLE
Block-Toolbar Style Issues

### ISSUE THREAD

**Issue by maethu** [4teamwork/ftw.simplelayout#134]
![screen shot 2015-06-18 at 08 04 46](https://cloud.githubusercontent.com/assets/437933/8225113/c4ef95ec-1590-11e5-9854-5880186f4b3f.png)

AND

The Block-Toolbar will be displayed, although the mouspointer is not on the block itself. Move the mouspointer towards a block from above and you will see what I mean.

**Comment by bierik** [comment]
Fixed through #138
