### ISSUE TITLE
Bildeinfügbereich im Editor-Overlay nicht sofort sichtbar

### ISSUE THREAD

**Issue by jounsiboss** [4teamwork/ftw.simplelayout#308]
Will man einem Textblock ein Bild hinzufügen, ist dies im Editor Overlay nicht sofort ersichtlich und schnell zu finden. Mann muss zuerst herunter Scrollen um zum nötigen Menüpunkt zu gelangen (s.Anhang). Optimaler wäre dies wohl in einem einzelnen Tab verfügbar zu machen.

![bildschirmfoto 2016-02-15 um 15 33 41](https://cloud.githubusercontent.com/assets/11310148/13051493/c641a138-d3f9-11e5-8f02-17a4fd80d250.png)
![bildschirmfoto 2016-02-15 um 15 33 58](https://cloud.githubusercontent.com/assets/11310148/13051500/cda5122a-d3f9-11e5-87d8-12a99e2ae9d6.png)

**Comment by bierik** [comment]
Fixed through https://github.com/4teamwork/ftw.simplelayout/pull/330 merci @jounsiboss
