### ISSUE TITLE
Simplelayout von Master funktioniert nicht mehr!

### ISSUE THREAD

**Issue by elioschmutz** [4teamwork/ftw.simplelayout#314]
![bildschirmfoto 2016-03-21 um 18 22 06](https://cloud.githubusercontent.com/assets/557005/13927409/e64deb86-ef91-11e5-9022-24da2986e244.png)

**Comment by jone** [comment]
https://github.com/4teamwork/ftw.simplelayout/blob/master/ftw/simplelayout/browser/resources/integration.theme.scss#L28-L29

**Comment by bierik** [comment]
Fixed throug https://github.com/4teamwork/ftw.simplelayout/commit/53f1e9a880d31cea0d3902e761ed056e6c55c467
