### ISSUE TITLE
gallery in portlet column too small

### ISSUE THREAD

**Issue by jone** [4teamwork/ftw.simplelayout#323]
When I add a gallery block in the right column, it is displayed with 4 images per row. This makes the images too small.
I'd like to have bigger images in a gallery in the portlet column.

![bildschirmfoto 2016-04-21 um 15 01 26](https://cloud.githubusercontent.com/assets/7469/14709785/b77c72ce-07d2-11e6-9e8d-6ee4a021343b.png)

// @bierik @maethu

**Comment by maethu** [comment]
I also would prefer 2 images per row in a two column layout.

**Comment by jone** [comment]
Maybe we could also support larger and smaller images, such as with the normal text block.

**Comment by maethu** [comment]
that would be cool!!

**Comment by jone** [comment]
Siehe https://github.com/4teamwork/ftw.simplelayout/pull/328
