### ISSUE TITLE
SL Portlet-Slot ist zu wenig Hoch

### ISSUE THREAD

**Issue by jone** [4teamwork/ftw.simplelayout#326]
![bildschirmfoto 2016-04-25 um 14 12 37](https://cloud.githubusercontent.com/assets/7469/14783436/e4895aa0-0aef-11e6-862a-cf79019c6b5f.png)

**Comment by bierik** [comment]
Die mindesthöhe der platzhalter wird nur gesetzt wenn die Klasse 'documentEditable' vorhanden ist. Ich denke dass diese Klasse nur für den Inhaltsbereich erreichbar ist und nicht für die Portletspalte

**Comment by jone** [comment]
Siehe https://github.com/4teamwork/ftw.simplelayout/pull/328
