### ISSUE TITLE
Background color on new element

### ISSUE THREAD

**Issue by raphael-s** [4teamwork/ftw.simplelayout#343]
When a new element has been created, it gets a white background. The problem here ist, that the css attribute gets added directly onto the `element.style` tag, which makes it impossible to overwrite with scss whithout using `!important`.

Example (fcs.web):
![bildschirmfoto 2016-06-03 um 11 33 10](https://cloud.githubusercontent.com/assets/16755391/15774863/00af94c6-297f-11e6-825f-9e1a66549da4.png)

**Comment by maethu** [comment]
@bierik Please fix this one soon. We now habe Issues in 3 different projects.
