### ISSUE TITLE
Adressblock - Bitte auf deutsch

### ISSUE THREAD

**Issue by brhi** [4teamwork/ftw.simplelayout#372]
![unbenannt](https://cloud.githubusercontent.com/assets/3796631/18158041/ee77f7e2-7020-11e6-9773-69f17fecf6ac.jpg)

**Comment by mbaechtold** [comment]
Ich schliesse das Ticket, weil es ein Duplikat von https://github.com/4teamwork/izug.organisation/issues/994 ist.
