### ISSUE TITLE
Rechte Spalte - Portlets optisch trennen

### ISSUE THREAD

**Issue by brhi** [4teamwork/ftw.simplelayout#373]
Bitte Portlets gemäss CD grau hinterlegen

**Comment by jone** [comment]
@brhi könntest du dies unter https://github.com/4teamwork/izug.organisation/issues erfassen? Dies gehört ins iZug, nicht allgemein zu Simplelayout 😉

**Comment by brhi** [comment]
@jone Martin hat mir gesagt, ihr würdet meine Fehlerfassungen übertragen.

**Comment by jone** [comment]
👍 ok, wusste ich nicht 😉
/cc @mbaechtold

**Comment by mbaechtold** [comment]
Ich schliesse dieses Ticket, das Thema wird in https://github.com/4teamwork/izug.organisation/issues/987 behandelt.
