### ISSUE TITLE
Inhaltsobjekt bearbeiten - Es fehlen noch die Legenden zu den Labels

### ISSUE THREAD

**Issue by brhi** [4teamwork/ftw.simplelayout#374]
![unbenannt](https://cloud.githubusercontent.com/assets/3796631/18158156/c3bde01a-7021-11e6-965b-c518aea83626.jpg)

**Comment by maethu** [comment]
@raphael-s please compare with descriptions from ftw.contenpage,

**Comment by raphael-s** [comment]
@maethu `ftw.contentpage` doesn't really have much more descriptions... should I add some by myself...?
See #380

**Comment by mbaechtold** [comment]
@raphael-s, the description and the translations of the alt text of the image can be found on https://github.com/4teamwork/ftw.contentpage/search?utf8=✓&q=description_image_alt_text:
- DE: Geben Sie den Alternativtext für das Bild ein. Der Alternativtext richtet sich an Benutzer und Endgeräte, die den Bildinhalt nicht wahrnehmen oder nicht darstellen können, und sollte also wörtlich als Alternative zum Bild formuliert sein. Falls kein Alternativtext angegeben wird, wird der Bildtitel verwendet.
- FR: Saisissez un texte alternatif pour l'image
Geben Sie den Alternativtext für das Bild ein. Der Alternativtext richtet sich an Benutzer und Endgeräte, die den Bildinhalt nicht wahrnehmen oder nicht darstellen können, und sollte also wörtlich als Alternative zum Bild formuliert sein. Falls kein Alternativtext angegeben wird, wird der Bildtitel verwendet.

And for the overlay option see https://github.com/4teamwork/ftw.contentpage/search?utf8=✓&q=description_image_clickable
- DE: Wird das Bild angeklickt, öffnet es sich in einem Overlay
- FR: Ouvre l'image dans un overlay
