### ISSUE TITLE
Inhaltsstruktur - Möglichkeit von "Spalten einrichten" einschränken

### ISSUE THREAD

**Issue by brhi** [4teamwork/ftw.simplelayout#375]
Stufe Webredaktoren: 1 Spalte
Stufe Webmaster: 2 und 4 Spalten

**Comment by maethu** [comment]
@brhi Diese Anforderung gehört IMHO in izug.organisation (https://github.com/4teamwork/izug.organisation)

**Comment by mbaechtold** [comment]
Ich habe das Ticket nach https://github.com/4teamwork/izug.organisation/issues/1004 übertragen.
