### ISSUE TITLE
Textblock bearbeiten - Element Inhalt standardmässig grösser darstellen

### ISSUE THREAD

**Issue by brhi** [4teamwork/ftw.simplelayout#376]
![unbenannt](https://cloud.githubusercontent.com/assets/3796631/18158236/4cdd9bec-7022-11e6-896b-8aaddfa6e1a1.jpg)

**Comment by mbaechtold** [comment]
@raphael-s, I think this is a HTML-Block.

**Comment by raphael-s** [comment]
The font-size for all the input fields in blocks is the same. So if we want to change it, we should change all of them and not just one.

**Comment by jone** [comment]
@raphael-s the font-size is ok, but the amount of visible lines is to low. This can be fixed with css `min-height: 8em`.

**Comment by raphael-s** [comment]
The textarea for the content of the html block has been enlarged in version `1.0.4` of `ftw.htmlblock`. Using the new version should fix this issue. ( @mbaechtold )
