### ISSUE TITLE
Veranstaltung - Keine saubere Bedienerführung

### ISSUE THREAD

**Issue by brhi** [4teamwork/ftw.simplelayout#377]
Ich kann einen Veranstaltungsordner hinzufügen. Auf der rechten Seite kann ich das Veranstaltungsportlet hinzufügen. Im Veranstaltungsordner kann ich eine Veranstaltung hinzufügen - hier ist jedoch das Inhaltsobjekt "Agenda" gemeint. 
![unbenannt](https://cloud.githubusercontent.com/assets/3796631/18158420/7dea1f16-7023-11e6-88fc-b23741e41639.jpg)

**Comment by jone** [comment]
Das `Veranstaltungen` rechts ist eigentlich ein Auflistungsblock von Veranstaltungen. Sollten wir den Block besser benennen, z.B.
- `Veranstaltungs-Liste`? 
- `Auflistung von Veranstaltungen`?
- `Liste von Veranstaltungen`?

**Comment by brhi** [comment]
@jone Können wir das am Donnerstag besprechen?

**Comment by jone** [comment]
👍 sicher!

**Comment by brhi** [comment]
sieht auch mit 2 Veranstaltungen nicht besser aus
![unbenannt](https://cloud.githubusercontent.com/assets/3796631/18275560/c9b2d2d0-7447-11e6-95c7-84f23b1a2c9e.jpg)

**Comment by raphael-s** [comment]
@brhi Habe den Issues mit @maethu angeschaut. Er meinte, es sei am besten wenn man das ebenfalls am Donnerstag anschaut.

(#378 )

**Comment by jone** [comment]
Dies haben wir mehrheitlich Projektspezifisch gelöst.
Konkret:
- Neues Zahnredli-Icon für das Bearbeiten des Auflistungsblockes.
- Neue Bezeichnung des Auflistungsblockes um Klarheit zu schaffen (https://github.com/4teamwork/ftw.events/pull/11)
- Umbenennung der Typen gemäss Kundenvorgaben.
