### ISSUE TITLE
Mapblock.js is not available for anonymous users

### ISSUE THREAD

**Issue by elioschmutz** [4teamwork/ftw.simplelayout#394]
According to https://github.com/4teamwork/ftw.simplelayout/blob/master/ftw/simplelayout/mapblock/profiles/default/jsregistry.xml#L7 the mapblock.js is not available for anonymous users.

Is there a reason for that?

If not, we should change it.

**Comment by maethu** [comment]
Unfortunately that's just wrong 😢
