### ISSUE TITLE
Too many blocks in toolbox

### ISSUE THREAD

**Issue by jone** [4teamwork/ftw.simplelayout#402]
When enabling a lot of blocks in the toolbar and working on a small screen, it may not be possible to add all layouts because the window is too little and the toolbox is not scrollable:
![bildschirmfoto 2016-11-24 um 08 43 11](https://cloud.githubusercontent.com/assets/7469/20590252/56487e62-b222-11e6-89bb-27ef7a5e816c.png)

How do we address this problem?

**1) Multi columns**
We could try to use multiple columns for the toolbar:
![bildschirmfoto 2016-11-24 um 09 06 35](https://cloud.githubusercontent.com/assets/7469/20590781/698970fa-b225-11e6-8f6f-80286ba30bbe.png)
This is probably not possible with CSS only though.

**2) Scrollable toolbar**
We could make the toolbar scrollable, but I think it is very confusing since we would have two scrollbars sometimes:
![bildschirmfoto 2016-11-24 um 09 11 45](https://cloud.githubusercontent.com/assets/7469/20590897/08ff98d0-b226-11e6-864e-10bb37a0cb0f.png)

**3) "More" submenu**
We could put "less important blocks" into a submenu (`...`). How would we decide which blocks are "less important", manually or automatically (e.g. `>5`)?
![bildschirmfoto 2016-11-24 um 09 18 20](https://cloud.githubusercontent.com/assets/7469/20591093/1b0711c4-b227-11e6-816a-cdd0f71b4287.png)

@maethu @bierik do you have any other ideas how to solve this problem?

**Comment by djowett** [comment]
That's a great problem to have - I guess you have to categorize your tiles ("Basic", "Media", ....) perhaps check what Google Sites does by comparison
