### ISSUE TITLE
Text block actions: named adapter

### ISSUE THREAD

**Issue by jone** [4teamwork/ftw.simplelayout#406]
The [TextBlockActions](https://github.com/4teamwork/ftw.simplelayout/blob/master/ftw/simplelayout/contenttypes/contents/configure.zcml#L34-L39) adapter is a _named_ adapter, containing the portal type as name:

```xml
    <adapter
        factory=".textblock.TextBlockActions"
        name="ftw-simplelayout-textblock-actions"
        for="*
             *"
        />
```

When I subclass the textblock (with a different `portal_type` name), the view will break with:
```python
  Module ftw.simplelayout.contenttypes.browser.textblock, line 119, in _get_default_actions
AttributeError: 'NoneType' object has no attribute 'specific_actions'
```

**Questions:**
1. Why is there no fallback implementation?
2. Why was it implemented with named adapters in the first place? As we are adapting the textblock, I would have used interfaces (`for="ITextBlock *"`).
3. [The code using the adapter](https://github.com/4teamwork/ftw.simplelayout/blob/master/ftw/simplelayout/contenttypes/browser/textblock.py#L115-L119) in the textblock view uses `queryMultiAdapter` and then always assumes it has an adapter. This is wrong: either `getMultiAdapter` should be used, or the `None`-case must be handled!

@maethu what do you think?

**Comment by maethu** [comment]
@jone I decided this design some approx. two years ago. 
I need to check this... hold on...
