### ISSUE TITLE
Unable to install upgrade step.

### ISSUE THREAD

**Issue by busykoala** [4teamwork/ftw.simplelayout#565]
While trying to upgrade ftw.simplelayout the error `ImportError: No module named IImagingSchema` can occur.

The error occurs in https://github.com/4teamwork/ftw.simplelayout/blob/master/ftw/simplelayout/contenttypes/upgrades/20191029182332_add_missing_image_scale/registry.xml

This can happen because the interface is not yet present in `CMFPlone 4.3.7` -> https://github.com/plone/Products.CMFPlone/blob/4.3.7/Products/CMFPlone/interfaces/controlpanel.py

**Comment by maethu** [comment]
This part of the upgrade step should only affect plone5

**Comment by maethu** [comment]
Ivest max 2h
