### ISSUE TITLE
Plone5: galleryblock overlay images have missing border

### ISSUE THREAD

**Issue by djowett-ftw** [4teamwork/ftw.simplelayout#604]
This occurs in production mode where merging the resources seems to duplicate the `++resource++` namespace within the URL

/* Start Bundle: ftw-colorbox-resources */
...
#cboxTopLeft{width:25px;height:25px;background:url(++resource++ftw.colorbox.resources/++resource++ftw.colorbox.resources/border1.png) no-repeat 0 0;}
....
/* End Bundle: ftw-colorbox-resources */

**Comment by maethu** [comment]
fixed in ftw.colorbox
